In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
u = np.array([2, 5])
v = np.array([3, 1])

In [3]:
u.dot(v)

11

In [4]:
np.dot(u, v)

11

In [5]:
A = np.array([
    [1, 2],
    [3, 4]
])
B = np.array([
    [3, 4, 5],
    [6, 7, 8]
])

In [6]:
A.dot(B)

array([[15, 18, 21],
       [33, 40, 47]])

In [7]:
np.dot(A, B)

array([[15, 18, 21],
       [33, 40, 47]])

In [8]:
A.shape

(2, 2)

In [9]:
B.shape

(2, 3)

In [10]:
A.dot(np.eye(2))

array([[1., 2.],
       [3., 4.]])

In [11]:
B.dot(np.eye(3))

array([[3., 4., 5.],
       [6., 7., 8.]])

In [12]:
np.eye(2).dot(B)

array([[3., 4., 5.],
       [6., 7., 8.]])

In [14]:
A.dot(A.T)

array([[ 5, 11],
       [11, 25]])

In [15]:
u.shape

(2,)

In [16]:
u.T

array([2, 5])

In [26]:
u[np.newaxis, :]

array([[2, 5]])

1D array转换为row vector, np.newaxis表明在垂直方向上申请一个新的轴，水平方向上为原来的所有元素

In [30]:
u[:, np.newaxis]

array([[2],
       [5]])

1D array转换为column vector, 垂直方向上为原来的所有元素，水平方向上申请一个新的轴

In [31]:
np.random.rand(100, 1)

array([[0.88867221],
       [0.10065719],
       [0.41234901],
       [0.40128301],
       [0.96195114],
       [0.06472667],
       [0.80162511],
       [0.42371459],
       [0.8199921 ],
       [0.97829908],
       [0.16906226],
       [0.7171026 ],
       [0.00687648],
       [0.90032518],
       [0.65667637],
       [0.7704934 ],
       [0.48049663],
       [0.46637136],
       [0.17056002],
       [0.10548008],
       [0.36425186],
       [0.74918548],
       [0.46420194],
       [0.15703502],
       [0.32587525],
       [0.78113738],
       [0.77086129],
       [0.60123825],
       [0.14738403],
       [0.41786386],
       [0.45098984],
       [0.59131341],
       [0.66362607],
       [0.45369796],
       [0.17501717],
       [0.74059735],
       [0.73197185],
       [0.85829729],
       [0.53455944],
       [0.11862389],
       [0.7031022 ],
       [0.67873204],
       [0.21566006],
       [0.61544847],
       [0.77224426],
       [0.18156769],
       [0.37855023],
       [0.702